const mongoose = require("mongoose");

const productSchema = new mongoose.Schema({
  title: String,
  image: Array,
  category: String,
  brand: String,
  price: Number,
  description: String,
  quantity: Number,
  model: String,
  offer: {
    offer_title: String,
    discount: String,
    offer_image: String,
  },
  specification: {
    volts: String,
    power_source: String,
    battery_type: String,
    max_torque: String,
    speed_settings: String,
    chuck_size: String,
    clutch_settings: String,
    safety_features: Array,
    compatibility: Array,
  },
  included_accessories: Array,
  weight: String,
  dimensions: String,
  warranty: String,
  color: Array,
  variant: Array,
  material: String,
  certification: String,
  usage: Array,
  recommended_applications: Array,
  features: Array,
  availability: String,
  shipping_weight: String,
  shipping_dimensions: String,
  shipping_restrictions: String,
  shipping_method: Array,
  assembly_required: Boolean,
  country_of_origin: String,
  manufacturer: String,
  return_available: Boolean,
  return_policy: String,
});

const Product = mongoose.model("Product", productSchema);
module.exports = Product;
